"""Emit the flattened model as a standalone file. OURS.

adevs has no equivalent of this file. It flattens only inside its own
simulator to run faster; the flat graph never leaves it. This is the step
Hazel described as missing: actually spitting out the resultant as a thing
you can hand someone.

What it writes (flat_pingpong.py): ONE atomic model class. A simulator sees
a single object with ta()/lam()/delta_int(); the two players and their
routing live inside as private state. The file imports nothing from this
repo — it is the whole flattened model.

Honest simplification: the transition logic below is specialized for the
Player (hit/catch). A general emitter would import the component classes
instead of inlining their logic — see devs-flatten's emit_executable.
"""

from pingpong import PingPong
from flatten import dissolve
import re

TEMPLATE = '''"""Flat ping-pong model -- generated by emit.py. Do not edit by hand.

ONE atomic model: the closure-under-coupling resultant. A simulator talks
to a single FlatPingPong with one ta(), one lam(), one delta_int(); the
two players and their direct routing live inside as private state.

Run it with:  python3 flat_pingpong.py
"""

INF = float("inf")
HIT_TIME = 1.0

# Initial state of each flat atomic, as plain data.
# (Was: Player objects nested inside the PingPong coupled model.)
ATOMICS = __ATOMICS__

# Direct routing: who sends to whom.
# (Was: the A<->B couplings declared on the coupled model.)
ROUTES = __ROUTES__


class FlatPingPong:
    """Single atomic interface over the flattened players."""

    def __init__(self):
        self.state = {p: dict(s) for p, s in ATOMICS.items()}

    def ta(self):
        # Minimum of the components' time advances (paper, Section 3).
        return min(s["sigma"] for s in self.state.values())

    def lam(self):
        # Pure preview of what the imminent players would output.
        if self.ta() == INF:
            return []
        return [(p, "ball") for p, s in self.state.items()
                if s["sigma"] == self.ta() and s["phase"] == "has_ball"]

    def delta_int(self):
        # The whole flat-graph step, internalized.
        sigma = self.ta()
        assert sigma != INF, "deadlock"
        for s in self.state.values():
            s["sigma"] -= sigma
        imminent = [p for p, s in self.state.items() if s["sigma"] == 0]
        bags = {}
        for p in imminent:
            if self.state[p]["phase"] == "has_ball":
                for d in ROUTES[p]:
                    bags.setdefault(d, []).append("ball")
        for p, s in self.state.items():
            if p in imminent:      # the hit
                s["phase"] = "no_ball"
                s["sigma"] = INF
            if p in bags:          # the catch
                s["phase"] = "has_ball"
                s["sigma"] = HIT_TIME

    def run(self, hits=6):
        time = 0.0
        trace = []
        for _ in range(hits):
            time += self.ta()
            trace.extend((time, p, o) for p, o in self.lam())
            self.delta_int()
        return trace


if __name__ == "__main__":
    for t, src, out in FlatPingPong().run():
        print("t=%g  %s -> %s" % (t, src, out))
'''


def emit(path="flat_pingpong.py"):
    atomics, edges = dissolve(PingPong())

    # Snapshot each flat atomic's initial state as plain data.
    snapshots = {p: {"phase": a.phase, "sigma": a.sigma}
                 for p, a in atomics.items()}

    # Collapse the edge list into a routing table.
    routes = {}
    for src, dst in edges:
        routes.setdefault(src, []).append(dst)

    src = (TEMPLATE
           .replace("__ATOMICS__", re.sub(r"\binf\b", "INF", repr(snapshots)))
           .replace("__ROUTES__", repr(routes)))
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"emitted 1 atomic model ({len(atomics)} internal components, "
          f"{sum(len(d) for d in routes.values())} routes) -> {path}")


if __name__ == "__main__":
    emit()
