# ours: writes the resultant out as a standalone file. adevs has no
# equivalent of this step; it only flattens inside its own simulator.
from pingpong import PingPong
from flatten import dissolve

TEMPLATE = '''"""Flat ping-pong, generated by emit.py. One atomic model: the simulator
sees a single FlatPingPong with ta/lam/delta_int; the two players live
inside as private state. Run: python3 flat_pingpong.py
"""

INF = float("inf")
HIT_TIME = 1.0

ATOMICS = __ATOMICS__  # each player's starting phase and timer
ROUTES = __ROUTES__    # who sends to whom, directly


class FlatPingPong:
    def __init__(self):
        self.state = {p: dict(s) for p, s in ATOMICS.items()}

    def ta(self):
        return min(s["sigma"] for s in self.state.values())

    def lam(self):
        if self.ta() == INF:
            return []
        return [(p, "ball") for p, s in self.state.items()
                if s["sigma"] == self.ta() and s["phase"] == "has_ball"]

    def delta_int(self):
        sigma = self.ta()
        for s in self.state.values():
            s["sigma"] -= sigma
        imminent = [p for p, s in self.state.items() if s["sigma"] == 0]
        bags = {}
        for p in imminent:
            if self.state[p]["phase"] == "has_ball":
                for d in ROUTES[p]:
                    bags.setdefault(d, []).append("ball")
        for p, s in self.state.items():
            if p in imminent:  # the hit
                s["phase"] = "no_ball"
                s["sigma"] = INF
            if p in bags:  # the catch
                s["phase"] = "has_ball"
                s["sigma"] = HIT_TIME

    def run(self, hits=6):
        time, trace = 0.0, []
        for _ in range(hits):
            time += self.ta()
            trace.extend((time, p, o) for p, o in self.lam())
            self.delta_int()
        return trace


if __name__ == "__main__":
    for t, src, out in FlatPingPong().run():
        print("t=%g  %s -> %s" % (t, src, out))
'''


def emit(path="flat_pingpong.py"):
    atomics, edges = dissolve(PingPong())
    snapshots = {p: {"phase": a.phase, "sigma": a.sigma}
                 for p, a in atomics.items()}
    routes = {}
    for src, dst in edges:
        routes.setdefault(src, []).append(dst)
    src = (TEMPLATE
           .replace("__ATOMICS__", repr(snapshots).replace("inf", "INF"))
           .replace("__ROUTES__", repr(routes)))
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    print("wrote", path)


if __name__ == "__main__":
    emit()
