"""Emit the flattened model as a standalone file. OURS.
adevs has no equivalent of this file. It flattens only inside its own
simulator to run faster; the flat graph never leaves it. This is the step
Hazel described as missing: actually spitting out the resultant as a thing
you can hand someone.

What it does: dissolve the coupled model, snapshot each flat atomic's
initial state as plain data, and write flat_pingpong.py containing the
states, the direct routing table, and a minimal runner. The output file
imports nothing from this repo — it is the whole flattened model.
"""

from pingpong import PingPong
from flatten import dissolve
import re

TEMPLATE = '''"""Flat ping-pong model -- generated by emit.py. Do not edit by hand.

The entire coupled model, flattened: __N__ atomics, direct routing,
no hierarchy. Run it with:  python3 flat_pingpong.py
"""

INF = float("inf")

# Initial state of each flat atomic, as plain data.
# (Was: Player objects nested inside the PingPong coupled model.)
ATOMICS = __ATOMICS__

# Direct routing: who sends to whom.
# (Was: the A<->B couplings declared on the coupled model.)
ROUTES = __ROUTES__


def run(hits=6):
    state = {p: dict(s) for p, s in ATOMICS.items()}
    time = 0.0
    trace = []
    for _ in range(hits):
        # Smallest timer wins -- same rule as the FlatSimulator.
        sigma = min(s["sigma"] for s in state.values())
        time += sigma
        for s in state.values():
            s["sigma"] -= sigma
        imminent = [p for p, s in state.items() if s["sigma"] == 0]
        # Outputs routed directly.
        bags = {}
        for p in imminent:
            if state[p]["phase"] == "has_ball":
                trace.append((time, p, "ball"))
                for d in ROUTES[p]:
                    bags.setdefault(d, []).append("ball")
        # Transitions: the hit, then the catch.
        for p, s in state.items():
            if p in imminent:
                s["phase"] = "no_ball"
                s["sigma"] = INF
            if p in bags:
                s["phase"] = "has_ball"
                s["sigma"] = 1.0
    return trace


if __name__ == "__main__":
    for t, src, out in run():
        print("t=%g  %s -> %s" % (t, src, out))
'''


def emit(path="flat_pingpong.py"):
    atomics, edges = dissolve(PingPong())

    # Snapshot each flat atomic's initial state as plain data.
    snapshots = {p: {"phase": a.phase, "sigma": a.sigma}
                 for p, a in atomics.items()}

    # Collapse the edge list into a routing table.
    routes = {}
    for src, dst in edges:
        routes.setdefault(src, []).append(dst)

    src = (TEMPLATE
           .replace("__N__", str(len(atomics)))
           .replace("__ATOMICS__", re.sub(r"\binf\b", "INF", repr(snapshots)))
           .replace("__ROUTES__", repr(routes)))
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"emitted {len(atomics)} atomics, "
          f"{sum(len(d) for d in routes.values())} routes -> {path}")


if __name__ == "__main__":
    emit()
