"""Flat ping-pong model -- generated by emit.py. Do not edit by hand.

ONE atomic model: the closure-under-coupling resultant. A simulator talks
to a single FlatPingPong with one ta(), one lam(), one delta_int(); the
two players and their direct routing live inside as private state.

Run it with:  python3 flat_pingpong.py
"""

INF = float("inf")
HIT_TIME = 1.0

# Initial state of each flat atomic, as plain data.
# (Was: Player objects nested inside the PingPong coupled model.)
ATOMICS = {'A': {'phase': 'has_ball', 'sigma': 1.0}, 'B': {'phase': 'no_ball', 'sigma': INF}}

# Direct routing: who sends to whom.
# (Was: the A<->B couplings declared on the coupled model.)
ROUTES = {'A': ['B'], 'B': ['A']}


class FlatPingPong:
    """Single atomic interface over the flattened players."""

    def __init__(self):
        self.state = {p: dict(s) for p, s in ATOMICS.items()}

    def ta(self):
        # Minimum of the components' time advances (paper, Section 3).
        return min(s["sigma"] for s in self.state.values())

    def lam(self):
        # Pure preview of what the imminent players would output.
        if self.ta() == INF:
            return []
        return [(p, "ball") for p, s in self.state.items()
                if s["sigma"] == self.ta() and s["phase"] == "has_ball"]

    def delta_int(self):
        # The whole flat-graph step, internalized.
        sigma = self.ta()
        assert sigma != INF, "deadlock"
        for s in self.state.values():
            s["sigma"] -= sigma
        imminent = [p for p, s in self.state.items() if s["sigma"] == 0]
        bags = {}
        for p in imminent:
            if self.state[p]["phase"] == "has_ball":
                for d in ROUTES[p]:
                    bags.setdefault(d, []).append("ball")
        for p, s in self.state.items():
            if p in imminent:      # the hit
                s["phase"] = "no_ball"
                s["sigma"] = INF
            if p in bags:          # the catch
                s["phase"] = "has_ball"
                s["sigma"] = HIT_TIME

    def run(self, hits=6):
        time = 0.0
        trace = []
        for _ in range(hits):
            time += self.ta()
            trace.extend((time, p, o) for p, o in self.lam())
            self.delta_int()
        return trace


if __name__ == "__main__":
    for t, src, out in FlatPingPong().run():
        print("t=%g  %s -> %s" % (t, src, out))
