"""Flat ping-pong model -- generated by emit.py. Do not edit by hand.

The entire coupled model, flattened: 2 atomics, direct routing,
no hierarchy. Run it with:  python3 flat_pingpong.py
"""

INF = float("inf")

# Initial state of each flat atomic, as plain data.
# (Was: Player objects nested inside the PingPong coupled model.)
ATOMICS = {'A': {'phase': 'has_ball', 'sigma': 1.0}, 'B': {'phase': 'no_ball', 'sigma': INF}}

# Direct routing: who sends to whom.
# (Was: the A<->B couplings declared on the coupled model.)
ROUTES = {'A': ['B'], 'B': ['A']}


def run(hits=6):
    state = {p: dict(s) for p, s in ATOMICS.items()}
    time = 0.0
    trace = []
    for _ in range(hits):
        # Smallest timer wins -- same rule as the FlatSimulator.
        sigma = min(s["sigma"] for s in state.values())
        time += sigma
        for s in state.values():
            s["sigma"] -= sigma
        imminent = [p for p, s in state.items() if s["sigma"] == 0]
        # Outputs routed directly.
        bags = {}
        for p in imminent:
            if state[p]["phase"] == "has_ball":
                trace.append((time, p, "ball"))
                for d in ROUTES[p]:
                    bags.setdefault(d, []).append("ball")
        # Transitions: the hit, then the catch.
        for p, s in state.items():
            if p in imminent:
                s["phase"] = "no_ball"
                s["sigma"] = INF
            if p in bags:
                s["phase"] = "has_ball"
                s["sigma"] = 1.0
    return trace


if __name__ == "__main__":
    for t, src, out in run():
        print("t=%g  %s -> %s" % (t, src, out))
